#!/bin/bash
echo "🚀 Robdius Deployment Guide"
echo "=========================="
echo ""
echo "Karena CLI bermasalah, silakan deploy secara manual:"
echo ""
echo "1. Buka https://vercel.com/dashboard"
echo "2. Login dengan akun Vercel"
echo "3. Klik 'New Project'"
echo "4. Pilih 'Import Git Repository'"
echo "5. Hubungkan dengan GitHub dan pilih repository 'robdius'"
echo ""
echo "6. Atur Environment Variables di Vercel:"
echo "   =================================="
echo "   DATABASE_URL = postgres://4cc549d11b5f6dc2b17f5524b71dd80a4d5b34f89dc723b0e9b1abde63b564ac:sk_vnJcP9gChI41QTPzknIIL@db.prisma.io:5432/?sslmode=require"
echo ""
echo "   POSTGRES_URL = postgres://4cc549d11b5f6dc2b17f5524b71dd80a4d5b34f89dc723b0e9b1abde63b564ac:sk_vnJcP9gChI41QTPzknIIL@db.prisma.io:5432/?sslmode=require"
echo ""
echo "   REDIS_URL = redis://default:xaN1y8tBmuNZppr8zQwVCoHncQtFmaQc@redis-15703.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com:15703"
echo ""
echo "   JWT_SECRET = robdius-jwt-secret-production-2024-very-secure-key"
echo ""
echo "   SESSION_SECRET = robdius-session-secret-production-2024-very-secure-key"
echo ""
echo "   NODE_ENV = production"
echo ""
echo "7. Pengaturan Build:"
echo "   ==============="
echo "   Framework Preset: Other"
echo "   Root Directory: /"
echo "   Build Command: (kosongkan atau 'npm install')"
echo "   Output Directory: ."
echo "   Install Command: npm install"
echo ""
echo "8. Deploy!"
echo ""
echo "✅ Setelah deploy berhasil, aplikasi akan tersedia di:"
echo "   https://robdius.vercel.app"
echo ""
echo "🔧 Jika ada error, periksa logs di Vercel dashboard"
echo "📊 Database dan Redis sudah dikonfigurasi untuk production"
echo ""
echo "🎯 Project sudah siap untuk production dengan fitur:"
echo "   - Login sistem (admin & customer)"
echo "   - Dashboard modern"
echo "   - Database PostgreSQL"
echo "   - Redis caching"
echo "   - Responsive UI"
echo ""
